const mongoose = require('mongoose');

const DistrictS = new mongoose.Schema({
    DistrictId: Number,
    DistrictName: String,
    CityId: Number
});

const CityS = new mongoose.Schema({
    CityId: Number,
    CityName: String
});

const District = mongoose.model('District', DistrictS);
const City = mongoose.model('City', CityS);


const createDummyCity = () => {

    const cities  = [
        { CityId : 1, CityName : "Adana" },
        { CityId : 2, CityName : "Adıyaman" },
        { CityId : 3, CityName : "Afyonkarahisar" },
        { CityId : 4, CityName : "Ağrı" },
        { CityId : 5, CityName : "Amasya" },
        { CityId : 6, CityName : "Ankara" },
        { CityId : 7, CityName : "Antalya" },
        { CityId : 8, CityName : "Artvin" },
        { CityId : 9, CityName : "Aydın" },
        { CityId : 10, CityName : "Balıkesir" },
        { CityId : 11, CityName : "Bilecik" },
        { CityId : 12, CityName : "Bingöl" },
        { CityId : 13, CityName : "Bitlis" },
        { CityId : 14, CityName : "Bolu" },
        { CityId : 15, CityName : "Burdur" },
        { CityId : 16, CityName : "Bursa" },
        { CityId : 17, CityName : "Çanakkale" },
        { CityId : 18, CityName : "Çankırı" },
        { CityId : 19, CityName : "Çorum" },
        { CityId : 20, CityName : "Denizli" },
        { CityId : 21, CityName : "Diyarbakır" },
        { CityId : 22, CityName : "Edirne" },
        { CityId : 23, CityName : "Elazığ" },
        { CityId : 24, CityName : "Erzincan" },
        { CityId : 25, CityName : "Erzurum" },
        { CityId : 26, CityName : "Eskişehir" },
        { CityId : 27, CityName : "Gaziantep" },
        { CityId : 28, CityName : "Giresun" },
        { CityId : 29, CityName : "Gümüşhane" },
        { CityId : 30, CityName : "Hakkari" },
        { CityId : 31, CityName : "Hatay" },
        { CityId : 32, CityName : "Isparta" },
        { CityId : 33, CityName : "Mersin" },
        { CityId : 34, CityName : "İstanbul" },
        { CityId : 35, CityName : "İzmir" },
        { CityId : 36, CityName : "Kars" },
        { CityId : 37, CityName : "Kastamonu" },
        { CityId : 38, CityName : "Kayseri" },
        { CityId : 39, CityName : "Kırklareli" },
        { CityId : 40, CityName : "Kırşehir" },
        { CityId : 41, CityName : "Kocaeli" },
        { CityId : 42, CityName : "Konya" },
        { CityId : 43, CityName : "Kütahya" },
        { CityId : 44, CityName : "Malatya" },
        { CityId : 45, CityName : "Manisa" },
        { CityId : 46, CityName : "Kahramanmaraş" },
        { CityId : 47, CityName : "Mardin" },
        { CityId : 48, CityName : "Muğla" },
        { CityId : 49, CityName : "Muş" },
        { CityId : 50, CityName : "Nevşehir" },
        { CityId : 51, CityName : "Niğde" },
        { CityId : 52, CityName : "Ordu" },
        { CityId : 53, CityName : "Rize" },
        { CityId : 54, CityName : "Sakarya" },
        { CityId : 55, CityName : "Samsun" },
        { CityId : 56, CityName : "Siirt" },
        { CityId : 57, CityName : "Sinop" },
        { CityId : 58, CityName : "Sivas" },
        { CityId : 59, CityName : "Tekirdağ" },
        { CityId : 60, CityName : "Tokat" },
        { CityId : 61, CityName : "Trabzon" },
        { CityId : 62, CityName : "Tunceli" },
        { CityId : 63, CityName : "Şanlıurfa" },
        { CityId : 64, CityName : "Uşak" },
        { CityId : 65, CityName : "Van" },
        { CityId : 66, CityName : "Yozgat" },
        { CityId : 67, CityName : "Zonguldak" },
        { CityId : 68, CityName : "Aksaray" },
        { CityId : 69, CityName : "Bayburt" },
        { CityId : 70, CityName : "Karaman" },
        { CityId : 71, CityName : "Kırıkkale" },
        { CityId : 72, CityName : "Batman" },
        { CityId : 73, CityName : "Şırnak" },
        { CityId : 74, CityName : "Bartın" },
        { CityId : 75, CityName : "Ardahan" },
        { CityId : 76, CityName : "Iğdır" },
        { CityId : 77, CityName : "Yalova" },
        { CityId : 78, CityName : "Karabük" },
        { CityId : 79, CityName : "Kilis" },
        { CityId : 80, CityName : "Osmaniye" },
        { CityId : 81, CityName : "Düzce" }]; 
 return cities;    
}


const createDummyDistrict = () => {
    const districts = [
        { DistrictId : 1, DistrictName : "Seyhan", CityId : 1 },
        { DistrictId : 2, DistrictName : "Ceyhan", CityId : 1 },
        { DistrictId : 3, DistrictName : "Feke", CityId : 1 },
        { DistrictId : 4, DistrictName : "Karaisalı", CityId : 1 },
        { DistrictId : 5, DistrictName : "Karataş", CityId : 1 },
        { DistrictId : 6, DistrictName : "Kozan", CityId : 1 },
        { DistrictId : 7, DistrictName : "Pozantı", CityId : 1 },
        { DistrictId : 8, DistrictName : "Saimbeyli", CityId : 1 },
        { DistrictId : 9, DistrictName : "Tufanbeyli", CityId : 1 },
        { DistrictId : 10, DistrictName : "Yumurtalık", CityId : 1 },
        { DistrictId : 11, DistrictName : "Yüreğir", CityId : 1 },
        { DistrictId : 12, DistrictName : "Aladağ", CityId : 1 },
        { DistrictId : 13, DistrictName : "İmamoğlu", CityId : 1 },
        { DistrictId : 14, DistrictName : "Sarıçam", CityId : 1 },
        { DistrictId : 15, DistrictName : "Çukurova", CityId : 1 },
        { DistrictId : 16, DistrictName : "Adıyaman Merkez", CityId : 2 },
        { DistrictId : 17, DistrictName : "Besni", CityId : 2 },
        { DistrictId : 18, DistrictName : "Çelikhan", CityId : 2 },
        { DistrictId : 19, DistrictName : "Gerger", CityId : 2 },
        { DistrictId : 20, DistrictName : "Gölbaşı / Adıyaman", CityId : 2 },
        { DistrictId : 21, DistrictName : "Kahta", CityId : 2 },
        { DistrictId : 22, DistrictName : "Samsat", CityId : 2 },
        { DistrictId : 23, DistrictName : "Sincik", CityId : 2 },
        { DistrictId : 24, DistrictName : "Tut", CityId : 2 },
        { DistrictId : 25, DistrictName : "Afyonkarahisar Merkez", CityId : 3 },
        { DistrictId : 26, DistrictName : "Bolvadin", CityId : 3 },
        { DistrictId : 27, DistrictName : "Çay", CityId : 3 },
        { DistrictId : 28, DistrictName : "Dazkırı", CityId : 3 },
        { DistrictId : 29, DistrictName : "Dinar", CityId : 3 },
        { DistrictId : 30, DistrictName : "Emirdağ", CityId : 3 },
        { DistrictId : 31, DistrictName : "İhsaniye", CityId : 3 },
        { DistrictId : 32, DistrictName : "Sandıklı", CityId : 3 },
        { DistrictId : 33, DistrictName : "Sinanpaşa", CityId : 3 },
        { DistrictId : 34, DistrictName : "Sultandağı", CityId : 3 },
        { DistrictId : 35, DistrictName : "Şuhut", CityId : 3 },
        { DistrictId : 36, DistrictName : "Başmakçı", CityId : 3 },
        { DistrictId : 37, DistrictName : "Bayat / Afyonkarahisar", CityId : 3 },
        { DistrictId : 38, DistrictName : "İscehisar", CityId : 3 },
        { DistrictId : 39, DistrictName : "Çobanlar", CityId : 3 },
        { DistrictId : 40, DistrictName : "Evciler", CityId : 3 },
        { DistrictId : 41, DistrictName : "Hocalar", CityId : 3 },
        { DistrictId : 42, DistrictName : "Kızılören", CityId : 3 },
        { DistrictId : 43, DistrictName : "Ağrı Merkez", CityId : 4 },
        { DistrictId : 44, DistrictName : "Diyadin", CityId : 4 },
        { DistrictId : 45, DistrictName : "Doğubayazıt", CityId : 4 },
        { DistrictId : 46, DistrictName : "Eleşkirt", CityId : 4 },
        { DistrictId : 47, DistrictName : "Hamur", CityId : 4 },
        { DistrictId : 48, DistrictName : "Patnos", CityId : 4 },
        { DistrictId : 49, DistrictName : "Taşlıçay", CityId : 4 },
        { DistrictId : 50, DistrictName : "Tutak", CityId : 4 },
        { DistrictId : 51, DistrictName : "Amasya Merkez", CityId : 5 },
        { DistrictId : 52, DistrictName : "Göynücek", CityId : 5 },
        { DistrictId : 53, DistrictName : "Gümüşhacıköy", CityId : 5 },
        { DistrictId : 54, DistrictName : "Merzifon", CityId : 5 },
        { DistrictId : 55, DistrictName : "Suluova", CityId : 5 },
        { DistrictId : 56, DistrictName : "Taşova", CityId : 5 },
        { DistrictId : 57, DistrictName : "Hamamözü", CityId : 5 },
        { DistrictId : 58, DistrictName : "Altındağ", CityId : 6 },
        { DistrictId : 59, DistrictName : "Ayaş", CityId : 6 },
        { DistrictId : 60, DistrictName : "Bala", CityId : 6 },
        { DistrictId : 61, DistrictName : "Beypazarı", CityId : 6 },
        { DistrictId : 62, DistrictName : "Çamlıdere", CityId : 6 },
        { DistrictId : 63, DistrictName : "Çankaya", CityId : 6 },
        { DistrictId : 64, DistrictName : "Çubuk", CityId : 6 },
        { DistrictId : 65, DistrictName : "Elmadağ", CityId : 6 },
        { DistrictId : 66, DistrictName : "Güdül", CityId : 6 },
        { DistrictId : 67, DistrictName : "Haymana", CityId : 6 },
        { DistrictId : 68, DistrictName : "Kalecik", CityId : 6 },
        { DistrictId : 69, DistrictName : "Kızılcahamam", CityId : 6 },
        { DistrictId : 70, DistrictName : "Nallıhan", CityId : 6 },
        { DistrictId : 71, DistrictName : "Polatlı", CityId : 6 },
        { DistrictId : 72, DistrictName : "Şereflikoçhisar", CityId : 6 },
        { DistrictId : 73, DistrictName : "Yenimahalle", CityId : 6 },
        { DistrictId : 74, DistrictName : "Gölbaşı / Ankara", CityId : 6 },
        { DistrictId : 75, DistrictName : "Keçiören", CityId : 6 },
        { DistrictId : 76, DistrictName : "Mamak", CityId : 6 },
        { DistrictId : 77, DistrictName : "Sincan", CityId : 6 },
        { DistrictId : 78, DistrictName : "Kazan", CityId : 6 },
        { DistrictId : 79, DistrictName : "Akyurt", CityId : 6 },
        { DistrictId : 80, DistrictName : "Etimesgut", CityId : 6 },
        { DistrictId : 81, DistrictName : "Evren", CityId : 6 },
        { DistrictId : 82, DistrictName : "Pursaklar", CityId : 6 },
        { DistrictId : 83, DistrictName : "Akseki", CityId : 7 },
        { DistrictId : 84, DistrictName : "Alanya", CityId : 7 },
        { DistrictId : 85, DistrictName : "Elmalı", CityId : 7 },
        { DistrictId : 86, DistrictName : "Finike", CityId : 7 },
        { DistrictId : 87, DistrictName : "Gazipaşa", CityId : 7 },
        { DistrictId : 88, DistrictName : "Gündoğmuş", CityId : 7 },
        { DistrictId : 89, DistrictName : "Kaş", CityId : 7 },
        { DistrictId : 90, DistrictName : "Korkuteli", CityId : 7 },
        { DistrictId : 91, DistrictName : "Kumluca", CityId : 7 },
        { DistrictId : 92, DistrictName : "Manavgat", CityId : 7 },
        { DistrictId : 93, DistrictName : "Serik", CityId : 7 },
        { DistrictId : 94, DistrictName : "Demre", CityId : 7 },
        { DistrictId : 95, DistrictName : "İbradı", CityId : 7 },
        { DistrictId : 96, DistrictName : "Kemer / Antalya", CityId : 7 },
        { DistrictId : 97, DistrictName : "Aksu / Antalya", CityId : 7 },
        { DistrictId : 98, DistrictName : "Döşemealtı", CityId : 7 },
        { DistrictId : 99, DistrictName : "Kepez", CityId : 7 },
        { DistrictId : 100, DistrictName : "Konyaaltı", CityId : 7 },
        { DistrictId : 101, DistrictName : "Muratpaşa", CityId : 7 },
        { DistrictId : 102, DistrictName : "Ardanuç", CityId : 8 },
        { DistrictId : 103, DistrictName : "Arhavi", CityId : 8 },
        { DistrictId : 104, DistrictName : "Artvin Merkez", CityId : 8 },
        { DistrictId : 105, DistrictName : "Borçka", CityId : 8 },
        { DistrictId : 106, DistrictName : "Hopa", CityId : 8 },
        { DistrictId : 107, DistrictName : "Şavşat", CityId : 8 },
        { DistrictId : 108, DistrictName : "Yusufeli", CityId : 8 },
        { DistrictId : 109, DistrictName : "Murgul", CityId : 8 },
        { DistrictId : 110, DistrictName : "Bozdoğan", CityId : 9 },
        { DistrictId : 111, DistrictName : "Çine", CityId : 9 },
        { DistrictId : 112, DistrictName : "Germencik", CityId : 9 },
        { DistrictId : 113, DistrictName : "Karacasu", CityId : 9 },
        { DistrictId : 114, DistrictName : "Koçarlı", CityId : 9 },
        { DistrictId : 115, DistrictName : "Kuşadası", CityId : 9 },
        { DistrictId : 116, DistrictName : "Kuyucak", CityId : 9 },
        { DistrictId : 117, DistrictName : "Nazilli", CityId : 9 },
        { DistrictId : 118, DistrictName : "Söke", CityId : 9 },
        { DistrictId : 119, DistrictName : "Sultanhisar", CityId : 9 },
        { DistrictId : 120, DistrictName : "Yenipazar / Aydın", CityId : 9 },
        { DistrictId : 121, DistrictName : "Buharkent", CityId : 9 },
        { DistrictId : 122, DistrictName : "İncirliova", CityId : 9 },
        { DistrictId : 123, DistrictName : "Karpuzlu", CityId : 9 },
        { DistrictId : 124, DistrictName : "Köşk", CityId : 9 },
        { DistrictId : 125, DistrictName : "Didim", CityId : 9 },
        { DistrictId : 126, DistrictName : "Efeler", CityId : 9 },
        { DistrictId : 127, DistrictName : "Ayvalık", CityId : 10 },
        { DistrictId : 128, DistrictName : "Balya", CityId : 10 },
        { DistrictId : 129, DistrictName : "Bandırma", CityId : 10 },
        { DistrictId : 130, DistrictName : "Bigadiç", CityId : 10 },
        { DistrictId : 131, DistrictName : "Burhaniye", CityId : 10 },
        { DistrictId : 132, DistrictName : "Dursunbey", CityId : 10 },
        { DistrictId : 133, DistrictName : "Edremit / Balıkesir", CityId : 10 },
        { DistrictId : 134, DistrictName : "Erdek", CityId : 10 },
        { DistrictId : 135, DistrictName : "Gönen / Balıkesir", CityId : 10 },
        { DistrictId : 136, DistrictName : "Havran", CityId : 10 },
        { DistrictId : 137, DistrictName : "İvrindi", CityId : 10 },
        { DistrictId : 138, DistrictName : "Kepsut", CityId : 10 },
        { DistrictId : 139, DistrictName : "Manyas", CityId : 10 },
        { DistrictId : 140, DistrictName : "Savaştepe", CityId : 10 },
        { DistrictId : 141, DistrictName : "Sındırgı", CityId : 10 },
        { DistrictId : 142, DistrictName : "Susurluk", CityId : 10 },
        { DistrictId : 143, DistrictName : "Marmara", CityId : 10 },
        { DistrictId : 144, DistrictName : "Gömeç", CityId : 10 },
        { DistrictId : 145, DistrictName : "Altıeylül", CityId : 10 },
        { DistrictId : 146, DistrictName : "Karesi", CityId : 10 },
        { DistrictId : 147, DistrictName : "Bilecik Merkez", CityId : 11 },
        { DistrictId : 148, DistrictName : "Bozüyük", CityId : 11 },
        { DistrictId : 149, DistrictName : "Gölpazarı", CityId : 11 },
        { DistrictId : 150, DistrictName : "Osmaneli", CityId : 11 },
        { DistrictId : 151, DistrictName : "Pazaryeri", CityId : 11 },
        { DistrictId : 152, DistrictName : "Söğüt", CityId : 11 },
        { DistrictId : 153, DistrictName : "Yenipazar / Bilecik", CityId : 11 },
        { DistrictId : 154, DistrictName : "İnhisar", CityId : 11 },
        { DistrictId : 155, DistrictName : "Bingöl Merkez", CityId : 12 },
        { DistrictId : 156, DistrictName : "Genç", CityId : 12 },
        { DistrictId : 157, DistrictName : "Karlıova", CityId : 12 },
        { DistrictId : 158, DistrictName : "Kiğı", CityId : 12 },
        { DistrictId : 159, DistrictName : "Solhan", CityId : 12 },
        { DistrictId : 160, DistrictName : "Adaklı", CityId : 12 },
        { DistrictId : 161, DistrictName : "Yayladere", CityId : 12 },
        { DistrictId : 162, DistrictName : "Yedisu", CityId : 12 },
        { DistrictId : 163, DistrictName : "Adilcevaz", CityId : 13 },
        { DistrictId : 164, DistrictName : "Ahlat", CityId : 13 },
        { DistrictId : 165, DistrictName : "Bitlis Merkez", CityId : 13 },
        { DistrictId : 166, DistrictName : "Hizan", CityId : 13 },
        { DistrictId : 167, DistrictName : "Mutki", CityId : 13 },
        { DistrictId : 168, DistrictName : "Tatvan", CityId : 13 },
        { DistrictId : 169, DistrictName : "Güroymak", CityId : 13 },
        { DistrictId : 170, DistrictName : "Bolu Merkez", CityId : 14 },
        { DistrictId : 171, DistrictName : "Gerede", CityId : 14 },
        { DistrictId : 172, DistrictName : "Göynük", CityId : 14 },
        { DistrictId : 173, DistrictName : "Kıbrıscık", CityId : 14 },
        { DistrictId : 174, DistrictName : "Mengen", CityId : 14 },
        { DistrictId : 175, DistrictName : "Mudurnu", CityId : 14 },
        { DistrictId : 176, DistrictName : "Seben", CityId : 14 },
        { DistrictId : 177, DistrictName : "Dörtdivan", CityId : 14 },
        { DistrictId : 178, DistrictName : "Yeniçağa", CityId : 14 },
        { DistrictId : 179, DistrictName : "Ağlasun", CityId : 15 },
        { DistrictId : 180, DistrictName : "Bucak", CityId : 15 },
        { DistrictId : 181, DistrictName : "Burdur Merkez", CityId : 15 },
        { DistrictId : 182, DistrictName : "Gölhisar", CityId : 15 },
        { DistrictId : 183, DistrictName : "Tefenni", CityId : 15 },
        { DistrictId : 184, DistrictName : "Yeşilova", CityId : 15 },
        { DistrictId : 185, DistrictName : "Karamanlı", CityId : 15 },
        { DistrictId : 186, DistrictName : "Kemer / Burdur", CityId : 15 },
        { DistrictId : 187, DistrictName : "Altınyayla / Burdur", CityId : 15 },
        { DistrictId : 188, DistrictName : "Çavdır", CityId : 15 },
        { DistrictId : 189, DistrictName : "Çeltikçi", CityId : 15 },
        { DistrictId : 190, DistrictName : "Gemlik", CityId : 16 },
        { DistrictId : 191, DistrictName : "İnegöl", CityId : 16 },
        { DistrictId : 192, DistrictName : "İznik", CityId : 16 },
        { DistrictId : 193, DistrictName : "Karacabey", CityId : 16 },
        { DistrictId : 194, DistrictName : "Keles", CityId : 16 },
        { DistrictId : 195, DistrictName : "Mudanya", CityId : 16 },
        { DistrictId : 196, DistrictName : "Mustafakemalpaşa", CityId : 16 },
        { DistrictId : 197, DistrictName : "Orhaneli", CityId : 16 },
        { DistrictId : 198, DistrictName : "Orhangazi", CityId : 16 },
        { DistrictId : 199, DistrictName : "Yenişehir / Bursa", CityId : 16 },
        { DistrictId : 200, DistrictName : "Büyükorhan", CityId : 16 },
        { DistrictId : 201, DistrictName : "Harmancık", CityId : 16 },
        { DistrictId : 202, DistrictName : "Nilüfer", CityId : 16 },
        { DistrictId : 203, DistrictName : "Osmangazi", CityId : 16 },
        { DistrictId : 204, DistrictName : "Yıldırım", CityId : 16 },
        { DistrictId : 205, DistrictName : "Gürsu", CityId : 16 },
        { DistrictId : 206, DistrictName : "Kestel", CityId : 16 },
        { DistrictId : 207, DistrictName : "Ayvacık / Çanakkale", CityId : 17 },
        { DistrictId : 208, DistrictName : "Bayramiç", CityId : 17 },
        { DistrictId : 209, DistrictName : "Biga", CityId : 17 },
        { DistrictId : 210, DistrictName : "Bozcaada", CityId : 17 },
        { DistrictId : 211, DistrictName : "Çan", CityId : 17 },
        { DistrictId : 212, DistrictName : "Çanakkale Merkez", CityId : 17 },
        { DistrictId : 213, DistrictName : "Eceabat", CityId : 17 },
        { DistrictId : 214, DistrictName : "Ezine", CityId : 17 },
        { DistrictId : 215, DistrictName : "Gelibolu", CityId : 17 },
        { DistrictId : 216, DistrictName : "Gökçeada", CityId : 17 },
        { DistrictId : 217, DistrictName : "Lapseki", CityId : 17 },
        { DistrictId : 218, DistrictName : "Yenice / Çanakkale", CityId : 17 },
        { DistrictId : 219, DistrictName : "Çankırı Merkez", CityId : 18 },
        { DistrictId : 220, DistrictName : "Çerkeş", CityId : 18 },
        { DistrictId : 221, DistrictName : "Eldivan", CityId : 18 },
        { DistrictId : 222, DistrictName : "Ilgaz", CityId : 18 },
        { DistrictId : 223, DistrictName : "Kurşunlu", CityId : 18 },
        { DistrictId : 224, DistrictName : "Orta", CityId : 18 },
        { DistrictId : 225, DistrictName : "Şabanözü", CityId : 18 },
        { DistrictId : 226, DistrictName : "Yapraklı", CityId : 18 },
        { DistrictId : 227, DistrictName : "Atkaracalar", CityId : 18 },
        { DistrictId : 228, DistrictName : "Kızılırmak", CityId : 18 },
        { DistrictId : 229, DistrictName : "Bayramören", CityId : 18 },
        { DistrictId : 230, DistrictName : "Korgun", CityId : 18 },
        { DistrictId : 231, DistrictName : "Alaca", CityId : 19 },
        { DistrictId : 232, DistrictName : "Bayat / Çorum", CityId : 19 },
        { DistrictId : 233, DistrictName : "Çorum Merkez", CityId : 19 },
        { DistrictId : 234, DistrictName : "İskilip", CityId : 19 },
        { DistrictId : 235, DistrictName : "Kargı", CityId : 19 },
        { DistrictId : 236, DistrictName : "Mecitözü", CityId : 19 },
        { DistrictId : 237, DistrictName : "Ortaköy / Çorum", CityId : 19 },
        { DistrictId : 238, DistrictName : "Osmancık", CityId : 19 },
        { DistrictId : 239, DistrictName : "Sungurlu", CityId : 19 },
        { DistrictId : 240, DistrictName : "Boğazkale", CityId : 19 },
        { DistrictId : 241, DistrictName : "Uğurludağ", CityId : 19 },
        { DistrictId : 242, DistrictName : "Dodurga", CityId : 19 },
        { DistrictId : 243, DistrictName : "Laçin", CityId : 19 },
        { DistrictId : 244, DistrictName : "Oğuzlar", CityId : 19 },
        { DistrictId : 245, DistrictName : "Acıpayam", CityId : 20 },
        { DistrictId : 246, DistrictName : "Buldan", CityId : 20 },
        { DistrictId : 247, DistrictName : "Çal", CityId : 20 },
        { DistrictId : 248, DistrictName : "Çameli", CityId : 20 },
        { DistrictId : 249, DistrictName : "Çardak", CityId : 20 },
        { DistrictId : 250, DistrictName : "Çivril", CityId : 20 },
        { DistrictId : 251, DistrictName : "Güney", CityId : 20 },
        { DistrictId : 252, DistrictName : "Kale / Denizli", CityId : 20 },
        { DistrictId : 253, DistrictName : "Sarayköy", CityId : 20 },
        { DistrictId : 254, DistrictName : "Tavas", CityId : 20 },
        { DistrictId : 255, DistrictName : "Babadağ", CityId : 20 },
        { DistrictId : 256, DistrictName : "Bekilli", CityId : 20 },
        { DistrictId : 257, DistrictName : "Honaz", CityId : 20 },
        { DistrictId : 258, DistrictName : "Serinhisar", CityId : 20 },
        { DistrictId : 259, DistrictName : "Pamukkale", CityId : 20 },
        { DistrictId : 260, DistrictName : "Baklan", CityId : 20 },
        { DistrictId : 261, DistrictName : "Beyağaç", CityId : 20 },
        { DistrictId : 262, DistrictName : "Bozkurt / Denizli", CityId : 20 },
        { DistrictId : 263, DistrictName : "Merkezefendi", CityId : 20 },
        { DistrictId : 264, DistrictName : "Bismil", CityId : 21 },
        { DistrictId : 265, DistrictName : "Çermik", CityId : 21 },
        { DistrictId : 266, DistrictName : "Çınar", CityId : 21 },
        { DistrictId : 267, DistrictName : "Çüngüş", CityId : 21 },
        { DistrictId : 268, DistrictName : "Dicle", CityId : 21 },
        { DistrictId : 269, DistrictName : "Ergani", CityId : 21 },
        { DistrictId : 270, DistrictName : "Hani", CityId : 21 },
        { DistrictId : 271, DistrictName : "Hazro", CityId : 21 },
        { DistrictId : 272, DistrictName : "Kulp", CityId : 21 },
        { DistrictId : 273, DistrictName : "Lice", CityId : 21 },
        { DistrictId : 274, DistrictName : "Silvan", CityId : 21 },
        { DistrictId : 275, DistrictName : "Eğil", CityId : 21 },
        { DistrictId : 276, DistrictName : "Kocaköy", CityId : 21 },
        { DistrictId : 277, DistrictName : "Bağlar", CityId : 21 },
        { DistrictId : 278, DistrictName : "Kayapınar", CityId : 21 },
        { DistrictId : 279, DistrictName : "Sur", CityId : 21 },
        { DistrictId : 280, DistrictName : "Yenişehir / Diyarbakır", CityId : 21 },
        { DistrictId : 281, DistrictName : "Edirne Merkez", CityId : 22 },
        { DistrictId : 282, DistrictName : "Enez", CityId : 22 },
        { DistrictId : 283, DistrictName : "Havsa", CityId : 22 },
        { DistrictId : 284, DistrictName : "İpsala", CityId : 22 },
        { DistrictId : 285, DistrictName : "Keşan", CityId : 22 },
        { DistrictId : 286, DistrictName : "Lalapaşa", CityId : 22 },
        { DistrictId : 287, DistrictName : "Meriç", CityId : 22 },
        { DistrictId : 288, DistrictName : "Uzunköprü", CityId : 22 },
        { DistrictId : 289, DistrictName : "Süloğlu", CityId : 22 },
        { DistrictId : 290, DistrictName : "Ağın", CityId : 23 },
        { DistrictId : 291, DistrictName : "Baskil", CityId : 23 },
        { DistrictId : 292, DistrictName : "Elazığ Merkez", CityId : 23 },
        { DistrictId : 293, DistrictName : "Karakoçan", CityId : 23 },
        { DistrictId : 294, DistrictName : "Keban", CityId : 23 },
        { DistrictId : 295, DistrictName : "Maden", CityId : 23 },
        { DistrictId : 296, DistrictName : "Palu", CityId : 23 },
        { DistrictId : 297, DistrictName : "Sivrice", CityId : 23 },
        { DistrictId : 298, DistrictName : "Arıcak", CityId : 23 },
        { DistrictId : 299, DistrictName : "Kovancılar", CityId : 23 },
        { DistrictId : 300, DistrictName : "Alacakaya", CityId : 23 },
        { DistrictId : 301, DistrictName : "Çayırlı", CityId : 24 },
        { DistrictId : 302, DistrictName : "Erzincan Merkez", CityId : 24 },
        { DistrictId : 303, DistrictName : "İliç", CityId : 24 },
        { DistrictId : 304, DistrictName : "Kemah", CityId : 24 },
        { DistrictId : 305, DistrictName : "Kemaliye", CityId : 24 },
        { DistrictId : 306, DistrictName : "Refahiye", CityId : 24 },
        { DistrictId : 307, DistrictName : "Tercan", CityId : 24 },
        { DistrictId : 308, DistrictName : "Üzümlü", CityId : 24 },
        { DistrictId : 309, DistrictName : "Otlukbeli", CityId : 24 },
        { DistrictId : 310, DistrictName : "Aşkale", CityId : 25 },
        { DistrictId : 311, DistrictName : "Çat", CityId : 25 },
        { DistrictId : 312, DistrictName : "Hınıs", CityId : 25 },
        { DistrictId : 313, DistrictName : "Horasan", CityId : 25 },
        { DistrictId : 314, DistrictName : "İspir", CityId : 25 },
        { DistrictId : 315, DistrictName : "Karayazı", CityId : 25 },
        { DistrictId : 316, DistrictName : "Narman", CityId : 25 },
        { DistrictId : 317, DistrictName : "Oltu", CityId : 25 },
        { DistrictId : 318, DistrictName : "Olur", CityId : 25 },
        { DistrictId : 319, DistrictName : "Pasinler", CityId : 25 },
        { DistrictId : 320, DistrictName : "Şenkaya", CityId : 25 },
        { DistrictId : 321, DistrictName : "Tekman", CityId : 25 },
        { DistrictId : 322, DistrictName : "Tortum", CityId : 25 },
        { DistrictId : 323, DistrictName : "Karaçoban", CityId : 25 },
        { DistrictId : 324, DistrictName : "Uzundere", CityId : 25 },
        { DistrictId : 325, DistrictName : "Pazaryolu", CityId : 25 },
        { DistrictId : 326, DistrictName : "Aziziye", CityId : 25 },
        { DistrictId : 327, DistrictName : "Köprüköy", CityId : 25 },
        { DistrictId : 328, DistrictName : "Palandöken", CityId : 25 },
        { DistrictId : 329, DistrictName : "Yakutiye", CityId : 25 },
        { DistrictId : 330, DistrictName : "Çifteler", CityId : 26 },
        { DistrictId : 331, DistrictName : "Mahmudiye", CityId : 26 },
        { DistrictId : 332, DistrictName : "Mihalıççık", CityId : 26 },
        { DistrictId : 333, DistrictName : "Sarıcakaya", CityId : 26 },
        { DistrictId : 334, DistrictName : "Seyitgazi", CityId : 26 },
        { DistrictId : 335, DistrictName : "Sivrihisar", CityId : 26 },
        { DistrictId : 336, DistrictName : "Alpu", CityId : 26 },
        { DistrictId : 337, DistrictName : "Beylikova", CityId : 26 },
        { DistrictId : 338, DistrictName : "İnönü", CityId : 26 },
        { DistrictId : 339, DistrictName : "Günyüzü", CityId : 26 },
        { DistrictId : 340, DistrictName : "Han", CityId : 26 },
        { DistrictId : 341, DistrictName : "Mihalgazi", CityId : 26 },
        { DistrictId : 342, DistrictName : "Odunpazarı", CityId : 26 },
        { DistrictId : 343, DistrictName : "Tepebaşı", CityId : 26 },
        { DistrictId : 344, DistrictName : "Araban", CityId : 27 },
        { DistrictId : 345, DistrictName : "İslahiye", CityId : 27 },
        { DistrictId : 346, DistrictName : "Nizip", CityId : 27 },
        { DistrictId : 347, DistrictName : "Oğuzeli", CityId : 27 },
        { DistrictId : 348, DistrictName : "Yavuzeli", CityId : 27 },
        { DistrictId : 349, DistrictName : "Şahinbey", CityId : 27 },
        { DistrictId : 350, DistrictName : "Şehitkamil", CityId : 27 },
        { DistrictId : 351, DistrictName : "Karkamış", CityId : 27 },
        { DistrictId : 352, DistrictName : "Nurdağı", CityId : 27 },
        { DistrictId : 353, DistrictName : "Alucra", CityId : 28 },
        { DistrictId : 354, DistrictName : "Bulancak", CityId : 28 },
        { DistrictId : 355, DistrictName : "Dereli", CityId : 28 },
        { DistrictId : 356, DistrictName : "Espiye", CityId : 28 },
        { DistrictId : 357, DistrictName : "Eynesil", CityId : 28 },
        { DistrictId : 358, DistrictName : "Giresun Merkez", CityId : 28 },
        { DistrictId : 359, DistrictName : "Görele", CityId : 28 },
        { DistrictId : 360, DistrictName : "Keşap", CityId : 28 },
        { DistrictId : 361, DistrictName : "Şebinkarahisar", CityId : 28 },
        { DistrictId : 362, DistrictName : "Tirebolu", CityId : 28 },
        { DistrictId : 363, DistrictName : "Piraziz", CityId : 28 },
        { DistrictId : 364, DistrictName : "Yağlıdere", CityId : 28 },
        { DistrictId : 365, DistrictName : "Çamoluk", CityId : 28 },
        { DistrictId : 366, DistrictName : "Çanakçı", CityId : 28 },
        { DistrictId : 367, DistrictName : "Doğankent", CityId : 28 },
        { DistrictId : 368, DistrictName : "Güce", CityId : 28 },
        { DistrictId : 369, DistrictName : "Gümüşhane Merkez", CityId : 29 },
        { DistrictId : 370, DistrictName : "Kelkit", CityId : 29 },
        { DistrictId : 371, DistrictName : "Şiran", CityId : 29 },
        { DistrictId : 372, DistrictName : "Torul", CityId : 29 },
        { DistrictId : 373, DistrictName : "Köse", CityId : 29 },
        { DistrictId : 374, DistrictName : "Kürtün", CityId : 29 },
        { DistrictId : 375, DistrictName : "Çukurca", CityId : 30 },
        { DistrictId : 376, DistrictName : "Hakkari Merkez", CityId : 30 },
        { DistrictId : 377, DistrictName : "Şemdinli", CityId : 30 },
        { DistrictId : 378, DistrictName : "Yüksekova", CityId : 30 },
        { DistrictId : 379, DistrictName : "Altınözü", CityId : 31 },
        { DistrictId : 380, DistrictName : "Dörtyol", CityId : 31 },
        { DistrictId : 381, DistrictName : "Hassa", CityId : 31 },
        { DistrictId : 382, DistrictName : "İskenderun", CityId : 31 },
        { DistrictId : 383, DistrictName : "Kırıkhan", CityId : 31 },
        { DistrictId : 384, DistrictName : "Reyhanlı", CityId : 31 },
        { DistrictId : 385, DistrictName : "Samandağ", CityId : 31 },
        { DistrictId : 386, DistrictName : "Yayladağı", CityId : 31 },
        { DistrictId : 387, DistrictName : "Erzin", CityId : 31 },
        { DistrictId : 388, DistrictName : "Belen", CityId : 31 },
        { DistrictId : 389, DistrictName : "Kumlu", CityId : 31 },
        { DistrictId : 390, DistrictName : "Antakya", CityId : 31 },
        { DistrictId : 391, DistrictName : "Arsuz", CityId : 31 },
        { DistrictId : 392, DistrictName : "Defne", CityId : 31 },
        { DistrictId : 393, DistrictName : "Payas", CityId : 31 },
        { DistrictId : 394, DistrictName : "Atabey", CityId : 32 },
        { DistrictId : 395, DistrictName : "Eğirdir", CityId : 32 },
        { DistrictId : 396, DistrictName : "Gelendost", CityId : 32 },
        { DistrictId : 397, DistrictName : "Isparta Merkez", CityId : 32 },
        { DistrictId : 398, DistrictName : "Keçiborlu", CityId : 32 },
        { DistrictId : 399, DistrictName : "Senirkent", CityId : 32 },
        { DistrictId : 400, DistrictName : "Sütçüler", CityId : 32 },
        { DistrictId : 401, DistrictName : "Şarkikaraağaç", CityId : 32 },
        { DistrictId : 402, DistrictName : "Uluborlu", CityId : 32 },
        { DistrictId : 403, DistrictName : "Yalvaç", CityId : 32 },
        { DistrictId : 404, DistrictName : "Aksu / Isparta", CityId : 32 },
        { DistrictId : 405, DistrictName : "Gönen / Isparta", CityId : 32 },
        { DistrictId : 406, DistrictName : "Yenişarbademli", CityId : 32 },
        { DistrictId : 407, DistrictName : "Anamur", CityId : 33 },
        { DistrictId : 408, DistrictName : "Erdemli", CityId : 33 },
        { DistrictId : 409, DistrictName : "Gülnar", CityId : 33 },
        { DistrictId : 410, DistrictName : "Mut", CityId : 33 },
        { DistrictId : 411, DistrictName : "Silifke", CityId : 33 },
        { DistrictId : 412, DistrictName : "Tarsus", CityId : 33 },
        { DistrictId : 413, DistrictName : "Aydıncık / Mersin", CityId : 33 },
        { DistrictId : 414, DistrictName : "Bozyazı", CityId : 33 },
        { DistrictId : 415, DistrictName : "Çamlıyayla", CityId : 33 },
        { DistrictId : 416, DistrictName : "Akdeniz", CityId : 33 },
        { DistrictId : 417, DistrictName : "Mezitli", CityId : 33 },
        { DistrictId : 418, DistrictName : "Toroslar", CityId : 33 },
        { DistrictId : 419, DistrictName : "Yenişehir / Mersin", CityId : 33 },
        { DistrictId : 420, DistrictName : "Adalar", CityId : 34 },
        { DistrictId : 421, DistrictName : "Bakırköy", CityId : 34 },
        { DistrictId : 422, DistrictName : "Beşiktaş", CityId : 34 },
        { DistrictId : 423, DistrictName : "Beykoz", CityId : 34 },
        { DistrictId : 424, DistrictName : "Beyoğlu", CityId : 34 },
        { DistrictId : 425, DistrictName : "Çatalca", CityId : 34 },
        { DistrictId : 426, DistrictName : "Eyüp", CityId : 34 },
        { DistrictId : 427, DistrictName : "Fatih", CityId : 34 },
        { DistrictId : 428, DistrictName : "Gaziosmanpaşa", CityId : 34 },
        { DistrictId : 429, DistrictName : "Kadıköy", CityId : 34 },
        { DistrictId : 430, DistrictName : "Kartal", CityId : 34 },
        { DistrictId : 431, DistrictName : "Sarıyer", CityId : 34 },
        { DistrictId : 432, DistrictName : "Silivri", CityId : 34 },
        { DistrictId : 433, DistrictName : "Şile", CityId : 34 },
        { DistrictId : 434, DistrictName : "Şişli", CityId : 34 },
        { DistrictId : 435, DistrictName : "Üsküdar", CityId : 34 },
        { DistrictId : 436, DistrictName : "Zeytinburnu", CityId : 34 },
        { DistrictId : 437, DistrictName : "Büyükçekmece", CityId : 34 },
        { DistrictId : 438, DistrictName : "Kağıthane", CityId : 34 },
        { DistrictId : 439, DistrictName : "Küçükçekmece", CityId : 34 },
        { DistrictId : 440, DistrictName : "Pendik", CityId : 34 },
        { DistrictId : 441, DistrictName : "Ümraniye", CityId : 34 },
        { DistrictId : 442, DistrictName : "Bayrampaşa", CityId : 34 },
        { DistrictId : 443, DistrictName : "Avcılar", CityId : 34 },
        { DistrictId : 444, DistrictName : "Bağcılar", CityId : 34 },
        { DistrictId : 445, DistrictName : "Bahçelievler", CityId : 34 },
        { DistrictId : 446, DistrictName : "Güngören", CityId : 34 },
        { DistrictId : 447, DistrictName : "Maltepe", CityId : 34 },
        { DistrictId : 448, DistrictName : "Sultanbeyli", CityId : 34 },
        { DistrictId : 449, DistrictName : "Tuzla", CityId : 34 },
        { DistrictId : 450, DistrictName : "Esenler", CityId : 34 },
        { DistrictId : 451, DistrictName : "Arnavutköy", CityId : 34 },
        { DistrictId : 452, DistrictName : "Ataşehir", CityId : 34 },
        { DistrictId : 453, DistrictName : "Başakşehir", CityId : 34 },
        { DistrictId : 454, DistrictName : "Beylikdüzü", CityId : 34 },
        { DistrictId : 455, DistrictName : "Çekmeköy", CityId : 34 },
        { DistrictId : 456, DistrictName : "Esenyurt", CityId : 34 },
        { DistrictId : 457, DistrictName : "Sancaktepe", CityId : 34 },
        { DistrictId : 458, DistrictName : "Sultangazi", CityId : 34 },
        { DistrictId : 459, DistrictName : "Aliağa", CityId : 35 },
        { DistrictId : 460, DistrictName : "Bayındır", CityId : 35 },
        { DistrictId : 461, DistrictName : "Bergama", CityId : 35 },
        { DistrictId : 462, DistrictName : "Bornova", CityId : 35 },
        { DistrictId : 463, DistrictName : "Çeşme", CityId : 35 },
        { DistrictId : 464, DistrictName : "Dikili", CityId : 35 },
        { DistrictId : 465, DistrictName : "Foça", CityId : 35 },
        { DistrictId : 466, DistrictName : "Karaburun", CityId : 35 },
        { DistrictId : 467, DistrictName : "Karşıyaka", CityId : 35 },
        { DistrictId : 468, DistrictName : "Kemalpaşa / İzmir", CityId : 35 },
        { DistrictId : 469, DistrictName : "Kınık", CityId : 35 },
        { DistrictId : 470, DistrictName : "Kiraz", CityId : 35 },
        { DistrictId : 471, DistrictName : "Menemen", CityId : 35 },
        { DistrictId : 472, DistrictName : "Ödemiş", CityId : 35 },
        { DistrictId : 473, DistrictName : "Seferihisar", CityId : 35 },
        { DistrictId : 474, DistrictName : "Selçuk", CityId : 35 },
        { DistrictId : 475, DistrictName : "Tire", CityId : 35 },
        { DistrictId : 476, DistrictName : "Torbalı", CityId : 35 },
        { DistrictId : 477, DistrictName : "Urla", CityId : 35 },
        { DistrictId : 478, DistrictName : "Beydağ", CityId : 35 },
        { DistrictId : 479, DistrictName : "Buca", CityId : 35 },
        { DistrictId : 480, DistrictName : "Konak", CityId : 35 },
        { DistrictId : 481, DistrictName : "Menderes", CityId : 35 },
        { DistrictId : 482, DistrictName : "Balçova", CityId : 35 },
        { DistrictId : 483, DistrictName : "Çiğli", CityId : 35 },
        { DistrictId : 484, DistrictName : "Gaziemir", CityId : 35 },
        { DistrictId : 485, DistrictName : "Narlıdere", CityId : 35 },
        { DistrictId : 486, DistrictName : "Güzelbahçe", CityId : 35 },
        { DistrictId : 487, DistrictName : "Bayraklı", CityId : 35 },
        { DistrictId : 488, DistrictName : "Karabağlar", CityId : 35 },
        { DistrictId : 489, DistrictName : "Arpaçay", CityId : 36 },
        { DistrictId : 490, DistrictName : "Digor", CityId : 36 },
        { DistrictId : 491, DistrictName : "Kağızman", CityId : 36 },
        { DistrictId : 492, DistrictName : "Kars Merkez", CityId : 36 },
        { DistrictId : 493, DistrictName : "Sarıkamış", CityId : 36 },
        { DistrictId : 494, DistrictName : "Selim", CityId : 36 },
        { DistrictId : 495, DistrictName : "Susuz", CityId : 36 },
        { DistrictId : 496, DistrictName : "Akyaka", CityId : 36 },
        { DistrictId : 497, DistrictName : "Abana", CityId : 37 },
        { DistrictId : 498, DistrictName : "Araç", CityId : 37 },
        { DistrictId : 499, DistrictName : "Azdavay", CityId : 37 },
        { DistrictId : 500, DistrictName : "Bozkurt / Kastamonu", CityId : 37 },
        { DistrictId : 501, DistrictName : "Cide", CityId : 37 },
        { DistrictId : 502, DistrictName : "Çatalzeytin", CityId : 37 },
        { DistrictId : 503, DistrictName : "Daday", CityId : 37 },
        { DistrictId : 504, DistrictName : "Devrekani", CityId : 37 },
        { DistrictId : 505, DistrictName : "İnebolu", CityId : 37 },
        { DistrictId : 506, DistrictName : "Kastamonu Merkez", CityId : 37 },
        { DistrictId : 507, DistrictName : "Küre", CityId : 37 },
        { DistrictId : 508, DistrictName : "Taşköprü", CityId : 37 },
        { DistrictId : 509, DistrictName : "Tosya", CityId : 37 },
        { DistrictId : 510, DistrictName : "İhsangazi", CityId : 37 },
        { DistrictId : 511, DistrictName : "Pınarbaşı / Kastamonu", CityId : 37 },
        { DistrictId : 512, DistrictName : "Şenpazar", CityId : 37 },
        { DistrictId : 513, DistrictName : "Ağlı", CityId : 37 },
        { DistrictId : 514, DistrictName : "Doğanyurt", CityId : 37 },
        { DistrictId : 515, DistrictName : "Hanönü", CityId : 37 },
        { DistrictId : 516, DistrictName : "Seydiler", CityId : 37 },
        { DistrictId : 517, DistrictName : "Bünyan", CityId : 38 },
        { DistrictId : 518, DistrictName : "Develi", CityId : 38 },
        { DistrictId : 519, DistrictName : "Felahiye", CityId : 38 },
        { DistrictId : 520, DistrictName : "İncesu", CityId : 38 },
        { DistrictId : 521, DistrictName : "Pınarbaşı / Kayseri", CityId : 38 },
        { DistrictId : 522, DistrictName : "Sarıoğlan", CityId : 38 },
        { DistrictId : 523, DistrictName : "Sarız", CityId : 38 },
        { DistrictId : 524, DistrictName : "Tomarza", CityId : 38 },
        { DistrictId : 525, DistrictName : "Yahyalı", CityId : 38 },
        { DistrictId : 526, DistrictName : "Yeşilhisar", CityId : 38 },
        { DistrictId : 527, DistrictName : "Akkışla", CityId : 38 },
        { DistrictId : 528, DistrictName : "Talas", CityId : 38 },
        { DistrictId : 529, DistrictName : "Kocasinan", CityId : 38 },
        { DistrictId : 530, DistrictName : "Melikgazi", CityId : 38 },
        { DistrictId : 531, DistrictName : "Hacılar", CityId : 38 },
        { DistrictId : 532, DistrictName : "Özvatan", CityId : 38 },
        { DistrictId : 533, DistrictName : "Babaeski", CityId : 39 },
        { DistrictId : 534, DistrictName : "Demirköy", CityId : 39 },
        { DistrictId : 535, DistrictName : "Kırklareli Merkez", CityId : 39 },
        { DistrictId : 536, DistrictName : "Kofçaz", CityId : 39 },
        { DistrictId : 537, DistrictName : "Lüleburgaz", CityId : 39 },
        { DistrictId : 538, DistrictName : "Pehlivanköy", CityId : 39 },
        { DistrictId : 539, DistrictName : "Pınarhisar", CityId : 39 },
        { DistrictId : 540, DistrictName : "Vize", CityId : 39 },
        { DistrictId : 541, DistrictName : "Çiçekdağı", CityId : 40 },
        { DistrictId : 542, DistrictName : "Kaman", CityId : 40 },
        { DistrictId : 543, DistrictName : "Kırşehir Merkez", CityId : 40 },
        { DistrictId : 544, DistrictName : "Mucur", CityId : 40 },
        { DistrictId : 545, DistrictName : "Akpınar", CityId : 40 },
        { DistrictId : 546, DistrictName : "Akçakent", CityId : 40 },
        { DistrictId : 547, DistrictName : "Boztepe", CityId : 40 },
        { DistrictId : 548, DistrictName : "Gebze", CityId : 41 },
        { DistrictId : 549, DistrictName : "Gölcük", CityId : 41 },
        { DistrictId : 550, DistrictName : "Kandıra", CityId : 41 },
        { DistrictId : 551, DistrictName : "Karamürsel", CityId : 41 },
        { DistrictId : 552, DistrictName : "Körfez", CityId : 41 },
        { DistrictId : 553, DistrictName : "Derince", CityId : 41 },
        { DistrictId : 554, DistrictName : "Başiskele", CityId : 41 },
        { DistrictId : 555, DistrictName : "Çayırova", CityId : 41 },
        { DistrictId : 556, DistrictName : "Darıca", CityId : 41 },
        { DistrictId : 557, DistrictName : "Dilovası", CityId : 41 },
        { DistrictId : 558, DistrictName : "İzmit", CityId : 41 },
        { DistrictId : 559, DistrictName : "Kartepe", CityId : 41 },
        { DistrictId : 560, DistrictName : "Akşehir", CityId : 42 },
        { DistrictId : 561, DistrictName : "Beyşehir", CityId : 42 },
        { DistrictId : 562, DistrictName : "Bozkır", CityId : 42 },
        { DistrictId : 563, DistrictName : "Cihanbeyli", CityId : 42 },
        { DistrictId : 564, DistrictName : "Çumra", CityId : 42 },
        { DistrictId : 565, DistrictName : "Doğanhisar", CityId : 42 },
        { DistrictId : 566, DistrictName : "Ereğli / Konya", CityId : 42 },
        { DistrictId : 567, DistrictName : "Hadim", CityId : 42 },
        { DistrictId : 568, DistrictName : "Ilgın", CityId : 42 },
        { DistrictId : 569, DistrictName : "Kadınhanı", CityId : 42 },
        { DistrictId : 570, DistrictName : "Karapınar", CityId : 42 },
        { DistrictId : 571, DistrictName : "Kulu", CityId : 42 },
        { DistrictId : 572, DistrictName : "Sarayönü", CityId : 42 },
        { DistrictId : 573, DistrictName : "Seydişehir", CityId : 42 },
        { DistrictId : 574, DistrictName : "Yunak", CityId : 42 },
        { DistrictId : 575, DistrictName : "Akören", CityId : 42 },
        { DistrictId : 576, DistrictName : "Altınekin", CityId : 42 },
        { DistrictId : 577, DistrictName : "Derebucak", CityId : 42 },
        { DistrictId : 578, DistrictName : "Hüyük", CityId : 42 },
        { DistrictId : 579, DistrictName : "Karatay", CityId : 42 },
        { DistrictId : 580, DistrictName : "Meram", CityId : 42 },
        { DistrictId : 581, DistrictName : "Selçuklu", CityId : 42 },
        { DistrictId : 582, DistrictName : "Taşkent", CityId : 42 },
        { DistrictId : 583, DistrictName : "Ahırlı", CityId : 42 },
        { DistrictId : 584, DistrictName : "Çeltik", CityId : 42 },
        { DistrictId : 585, DistrictName : "Derbent", CityId : 42 },
        { DistrictId : 586, DistrictName : "Emirgazi", CityId : 42 },
        { DistrictId : 587, DistrictName : "Güneysınır", CityId : 42 },
        { DistrictId : 588, DistrictName : "Halkapınar", CityId : 42 },
        { DistrictId : 589, DistrictName : "Tuzlukçu", CityId : 42 },
        { DistrictId : 590, DistrictName : "Yalıhüyük", CityId : 42 },
        { DistrictId : 591, DistrictName : "Altıntaş", CityId : 43 },
        { DistrictId : 592, DistrictName : "Domaniç", CityId : 43 },
        { DistrictId : 593, DistrictName : "Emet", CityId : 43 },
        { DistrictId : 594, DistrictName : "Gediz", CityId : 43 },
        { DistrictId : 595, DistrictName : "Kütahya Merkez", CityId : 43 },
        { DistrictId : 596, DistrictName : "Simav", CityId : 43 },
        { DistrictId : 597, DistrictName : "Tavşanlı", CityId : 43 },
        { DistrictId : 598, DistrictName : "Aslanapa", CityId : 43 },
        { DistrictId : 599, DistrictName : "Dumlupınar", CityId : 43 },
        { DistrictId : 600, DistrictName : "Hisarcık", CityId : 43 },
        { DistrictId : 601, DistrictName : "Şaphane", CityId : 43 },
        { DistrictId : 602, DistrictName : "Çavdarhisar", CityId : 43 },
        { DistrictId : 603, DistrictName : "Pazarlar", CityId : 43 },
        { DistrictId : 604, DistrictName : "Akçadağ", CityId : 44 },
        { DistrictId : 605, DistrictName : "Arapgir", CityId : 44 },
        { DistrictId : 606, DistrictName : "Arguvan", CityId : 44 },
        { DistrictId : 607, DistrictName : "Darende", CityId : 44 },
        { DistrictId : 608, DistrictName : "Doğanşehir", CityId : 44 },
        { DistrictId : 609, DistrictName : "Hekimhan", CityId : 44 },
        { DistrictId : 610, DistrictName : "Pütürge", CityId : 44 },
        { DistrictId : 611, DistrictName : "Yeşilyurt / Malatya", CityId : 44 },
        { DistrictId : 612, DistrictName : "Battalgazi", CityId : 44 },
        { DistrictId : 613, DistrictName : "Doğanyol", CityId : 44 },
        { DistrictId : 614, DistrictName : "Kale / Malatya", CityId : 44 },
        { DistrictId : 615, DistrictName : "Kuluncak", CityId : 44 },
        { DistrictId : 616, DistrictName : "Yazıhan", CityId : 44 },
        { DistrictId : 617, DistrictName : "Akhisar", CityId : 45 },
        { DistrictId : 618, DistrictName : "Alaşehir", CityId : 45 },
        { DistrictId : 619, DistrictName : "Demirci", CityId : 45 },
        { DistrictId : 620, DistrictName : "Gördes", CityId : 45 },
        { DistrictId : 621, DistrictName : "Kırkağaç", CityId : 45 },
        { DistrictId : 622, DistrictName : "Kula", CityId : 45 },
        { DistrictId : 623, DistrictName : "Salihli", CityId : 45 },
        { DistrictId : 624, DistrictName : "Sarıgöl", CityId : 45 },
        { DistrictId : 625, DistrictName : "Saruhanlı", CityId : 45 },
        { DistrictId : 626, DistrictName : "Selendi", CityId : 45 },
        { DistrictId : 627, DistrictName : "Soma", CityId : 45 },
        { DistrictId : 628, DistrictName : "Turgutlu", CityId : 45 },
        { DistrictId : 629, DistrictName : "Ahmetli", CityId : 45 },
        { DistrictId : 630, DistrictName : "Gölmarmara", CityId : 45 },
        { DistrictId : 631, DistrictName : "Köprübaşı / Manisa", CityId : 45 },
        { DistrictId : 632, DistrictName : "Şehzadeler", CityId : 45 },
        { DistrictId : 633, DistrictName : "Yunusemre", CityId : 45 },
        { DistrictId : 634, DistrictName : "Afşin", CityId : 46 },
        { DistrictId : 635, DistrictName : "Andırın", CityId : 46 },
        { DistrictId : 636, DistrictName : "Elbistan", CityId : 46 },
        { DistrictId : 637, DistrictName : "Göksun", CityId : 46 },
        { DistrictId : 638, DistrictName : "Pazarcık", CityId : 46 },
        { DistrictId : 639, DistrictName : "Türkoğlu", CityId : 46 },
        { DistrictId : 640, DistrictName : "Çağlayancerit", CityId : 46 },
        { DistrictId : 641, DistrictName : "Ekinözü", CityId : 46 },
        { DistrictId : 642, DistrictName : "Nurhak", CityId : 46 },
        { DistrictId : 643, DistrictName : "Dulkadiroğlu", CityId : 46 },
        { DistrictId : 644, DistrictName : "Onikişubat", CityId : 46 },
        { DistrictId : 645, DistrictName : "Derik", CityId : 47 },
        { DistrictId : 646, DistrictName : "Kızıltepe", CityId : 47 },
        { DistrictId : 647, DistrictName : "Mazıdağı", CityId : 47 },
        { DistrictId : 648, DistrictName : "Midyat", CityId : 47 },
        { DistrictId : 649, DistrictName : "Nusaybin", CityId : 47 },
        { DistrictId : 650, DistrictName : "Ömerli", CityId : 47 },
        { DistrictId : 651, DistrictName : "Savur", CityId : 47 },
        { DistrictId : 652, DistrictName : "Dargeçit", CityId : 47 },
        { DistrictId : 653, DistrictName : "Yeşilli", CityId : 47 },
        { DistrictId : 654, DistrictName : "Artuklu", CityId : 47 },
        { DistrictId : 655, DistrictName : "Bodrum", CityId : 48 },
        { DistrictId : 656, DistrictName : "Datça", CityId : 48 },
        { DistrictId : 657, DistrictName : "Fethiye", CityId : 48 },
        { DistrictId : 658, DistrictName : "Köyceğiz", CityId : 48 },
        { DistrictId : 659, DistrictName : "Marmaris", CityId : 48 },
        { DistrictId : 660, DistrictName : "Milas", CityId : 48 },
        { DistrictId : 661, DistrictName : "Ula", CityId : 48 },
        { DistrictId : 662, DistrictName : "Yatağan", CityId : 48 },
        { DistrictId : 663, DistrictName : "Dalaman", CityId : 48 },
        { DistrictId : 664, DistrictName : "Ortaca", CityId : 48 },
        { DistrictId : 665, DistrictName : "Kavaklıdere", CityId : 48 },
        { DistrictId : 666, DistrictName : "Menteşe", CityId : 48 },
        { DistrictId : 667, DistrictName : "Seydikemer", CityId : 48 },
        { DistrictId : 668, DistrictName : "Bulanık", CityId : 49 },
        { DistrictId : 669, DistrictName : "Malazgirt", CityId : 49 },
        { DistrictId : 670, DistrictName : "Muş Merkez", CityId : 49 },
        { DistrictId : 671, DistrictName : "Varto", CityId : 49 },
        { DistrictId : 672, DistrictName : "Hasköy", CityId : 49 },
        { DistrictId : 673, DistrictName : "Korkut", CityId : 49 },
        { DistrictId : 674, DistrictName : "Avanos", CityId : 50 },
        { DistrictId : 675, DistrictName : "Derinkuyu", CityId : 50 },
        { DistrictId : 676, DistrictName : "Gülşehir", CityId : 50 },
        { DistrictId : 677, DistrictName : "Hacıbektaş", CityId : 50 },
        { DistrictId : 678, DistrictName : "Kozaklı", CityId : 50 },
        { DistrictId : 679, DistrictName : "Nevşehir Merkez", CityId : 50 },
        { DistrictId : 680, DistrictName : "Ürgüp", CityId : 50 },
        { DistrictId : 681, DistrictName : "Acıgöl", CityId : 50 },
        { DistrictId : 682, DistrictName : "Bor", CityId : 51 },
        { DistrictId : 683, DistrictName : "Çamardı", CityId : 51 },
        { DistrictId : 684, DistrictName : "Niğde Merkez", CityId : 51 },
        { DistrictId : 685, DistrictName : "Ulukışla", CityId : 51 },
        { DistrictId : 686, DistrictName : "Altunhisar", CityId : 51 },
        { DistrictId : 687, DistrictName : "Çiftlik", CityId : 51 },
        { DistrictId : 688, DistrictName : "Akkuş", CityId : 52 },
        { DistrictId : 689, DistrictName : "Aybastı", CityId : 52 },
        { DistrictId : 690, DistrictName : "Fatsa", CityId : 52 },
        { DistrictId : 691, DistrictName : "Gölköy", CityId : 52 },
        { DistrictId : 692, DistrictName : "Korgan", CityId : 52 },
        { DistrictId : 693, DistrictName : "Kumru", CityId : 52 },
        { DistrictId : 694, DistrictName : "Mesudiye", CityId : 52 },
        { DistrictId : 695, DistrictName : "Perşembe", CityId : 52 },
        { DistrictId : 696, DistrictName : "Ulubey / Ordu", CityId : 52 },
        { DistrictId : 697, DistrictName : "Ünye", CityId : 52 },
        { DistrictId : 698, DistrictName : "Gülyalı", CityId : 52 },
        { DistrictId : 699, DistrictName : "Gürgentepe", CityId : 52 },
        { DistrictId : 700, DistrictName : "Çamaş", CityId : 52 },
        { DistrictId : 701, DistrictName : "Çatalpınar", CityId : 52 },
        { DistrictId : 702, DistrictName : "Çaybaşı", CityId : 52 },
        { DistrictId : 703, DistrictName : "İkizce", CityId : 52 },
        { DistrictId : 704, DistrictName : "Kabadüz", CityId : 52 },
        { DistrictId : 705, DistrictName : "Kabataş", CityId : 52 },
        { DistrictId : 706, DistrictName : "Altınordu", CityId : 52 },
        { DistrictId : 707, DistrictName : "Ardeşen", CityId : 53 },
        { DistrictId : 708, DistrictName : "Çamlıhemşin", CityId : 53 },
        { DistrictId : 709, DistrictName : "Çayeli", CityId : 53 },
        { DistrictId : 710, DistrictName : "Fındıklı", CityId : 53 },
        { DistrictId : 711, DistrictName : "İkizdere", CityId : 53 },
        { DistrictId : 712, DistrictName : "Kalkandere", CityId : 53 },
        { DistrictId : 713, DistrictName : "Pazar / Rize", CityId : 53 },
        { DistrictId : 714, DistrictName : "Rize Merkez", CityId : 53 },
        { DistrictId : 715, DistrictName : "Güneysu", CityId : 53 },
        { DistrictId : 716, DistrictName : "Derepazarı", CityId : 53 },
        { DistrictId : 717, DistrictName : "Hemşin", CityId : 53 },
        { DistrictId : 718, DistrictName : "İyidere", CityId : 53 },
        { DistrictId : 719, DistrictName : "Akyazı", CityId : 54 },
        { DistrictId : 720, DistrictName : "Geyve", CityId : 54 },
        { DistrictId : 721, DistrictName : "Hendek", CityId : 54 },
        { DistrictId : 722, DistrictName : "Karasu", CityId : 54 },
        { DistrictId : 723, DistrictName : "Kaynarca", CityId : 54 },
        { DistrictId : 724, DistrictName : "Sapanca", CityId : 54 },
        { DistrictId : 725, DistrictName : "Kocaali", CityId : 54 },
        { DistrictId : 726, DistrictName : "Pamukova", CityId : 54 },
        { DistrictId : 727, DistrictName : "Taraklı", CityId : 54 },
        { DistrictId : 728, DistrictName : "Ferizli", CityId : 54 },
        { DistrictId : 729, DistrictName : "Karapürçek", CityId : 54 },
        { DistrictId : 730, DistrictName : "Söğütlü", CityId : 54 },
        { DistrictId : 731, DistrictName : "Adapazarı", CityId : 54 },
        { DistrictId : 732, DistrictName : "Arifiye", CityId : 54 },
        { DistrictId : 733, DistrictName : "Erenler", CityId : 54 },
        { DistrictId : 734, DistrictName : "Serdivan", CityId : 54 },
        { DistrictId : 735, DistrictName : "Alaçam", CityId : 55 },
        { DistrictId : 736, DistrictName : "Bafra", CityId : 55 },
        { DistrictId : 737, DistrictName : "Çarşamba", CityId : 55 },
        { DistrictId : 738, DistrictName : "Havza", CityId : 55 },
        { DistrictId : 739, DistrictName : "Kavak", CityId : 55 },
        { DistrictId : 740, DistrictName : "Ladik", CityId : 55 },
        { DistrictId : 741, DistrictName : "Terme", CityId : 55 },
        { DistrictId : 742, DistrictName : "Vezirköprü", CityId : 55 },
        { DistrictId : 743, DistrictName : "Asarcık", CityId : 55 },
        { DistrictId : 744, DistrictName : "43604", CityId : 55 },
        { DistrictId : 745, DistrictName : "Salıpazarı", CityId : 55 },
        { DistrictId : 746, DistrictName : "Tekkeköy", CityId : 55 },
        { DistrictId : 747, DistrictName : "Ayvacık / Samsun", CityId : 55 },
        { DistrictId : 748, DistrictName : "Yakakent", CityId : 55 },
        { DistrictId : 749, DistrictName : "Atakum", CityId : 55 },
        { DistrictId : 750, DistrictName : "Canik", CityId : 55 },
        { DistrictId : 751, DistrictName : "İlkadım", CityId : 55 },
        { DistrictId : 752, DistrictName : "Baykan", CityId : 56 },
        { DistrictId : 753, DistrictName : "Eruh", CityId : 56 },
        { DistrictId : 754, DistrictName : "Kurtalan", CityId : 56 },
        { DistrictId : 755, DistrictName : "Pervari", CityId : 56 },
        { DistrictId : 756, DistrictName : "Siirt Merkez", CityId : 56 },
        { DistrictId : 757, DistrictName : "Şirvan", CityId : 56 },
        { DistrictId : 758, DistrictName : "Tillo", CityId : 56 },
        { DistrictId : 759, DistrictName : "Ayancık", CityId : 57 },
        { DistrictId : 760, DistrictName : "Boyabat", CityId : 57 },
        { DistrictId : 761, DistrictName : "Durağan", CityId : 57 },
        { DistrictId : 762, DistrictName : "Erfelek", CityId : 57 },
        { DistrictId : 763, DistrictName : "Gerze", CityId : 57 },
        { DistrictId : 764, DistrictName : "Sinop Merkez", CityId : 57 },
        { DistrictId : 765, DistrictName : "Türkeli", CityId : 57 },
        { DistrictId : 766, DistrictName : "Dikmen", CityId : 57 },
        { DistrictId : 767, DistrictName : "Saraydüzü", CityId : 57 },
        { DistrictId : 768, DistrictName : "Divriği", CityId : 58 },
        { DistrictId : 769, DistrictName : "Gemerek", CityId : 58 },
        { DistrictId : 770, DistrictName : "Gürün", CityId : 58 },
        { DistrictId : 771, DistrictName : "Hafik", CityId : 58 },
        { DistrictId : 772, DistrictName : "İmranlı", CityId : 58 },
        { DistrictId : 773, DistrictName : "Kangal", CityId : 58 },
        { DistrictId : 774, DistrictName : "Koyulhisar", CityId : 58 },
        { DistrictId : 775, DistrictName : "Sivas Merkez", CityId : 58 },
        { DistrictId : 776, DistrictName : "Suşehri", CityId : 58 },
        { DistrictId : 777, DistrictName : "Şarkışla", CityId : 58 },
        { DistrictId : 778, DistrictName : "Yıldızeli", CityId : 58 },
        { DistrictId : 779, DistrictName : "Zara", CityId : 58 },
        { DistrictId : 780, DistrictName : "Akıncılar", CityId : 58 },
        { DistrictId : 781, DistrictName : "Altınyayla / Sivas", CityId : 58 },
        { DistrictId : 782, DistrictName : "Doğanşar", CityId : 58 },
        { DistrictId : 783, DistrictName : "Gölova", CityId : 58 },
        { DistrictId : 784, DistrictName : "Ulaş", CityId : 58 },
        { DistrictId : 785, DistrictName : "Çerkezköy", CityId : 59 },
        { DistrictId : 786, DistrictName : "Çorlu", CityId : 59 },
        { DistrictId : 787, DistrictName : "Hayrabolu", CityId : 59 },
        { DistrictId : 788, DistrictName : "Malkara", CityId : 59 },
        { DistrictId : 789, DistrictName : "Muratlı", CityId : 59 },
        { DistrictId : 790, DistrictName : "Saray / Tekirdağ", CityId : 59 },
        { DistrictId : 791, DistrictName : "Şarköy", CityId : 59 },
        { DistrictId : 792, DistrictName : "Marmaraereğlisi", CityId : 59 },
        { DistrictId : 793, DistrictName : "Ergene", CityId : 59 },
        { DistrictId : 794, DistrictName : "Kapaklı", CityId : 59 },
        { DistrictId : 795, DistrictName : "Süleymanpaşa", CityId : 59 },
        { DistrictId : 796, DistrictName : "Almus", CityId : 60 },
        { DistrictId : 797, DistrictName : "Artova", CityId : 60 },
        { DistrictId : 798, DistrictName : "Erbaa", CityId : 60 },
        { DistrictId : 799, DistrictName : "Niksar", CityId : 60 },
        { DistrictId : 800, DistrictName : "Reşadiye", CityId : 60 },
        { DistrictId : 801, DistrictName : "Tokat Merkez", CityId : 60 },
        { DistrictId : 802, DistrictName : "Turhal", CityId : 60 },
        { DistrictId : 803, DistrictName : "Zile", CityId : 60 },
        { DistrictId : 804, DistrictName : "Pazar / Tokat", CityId : 60 },
        { DistrictId : 805, DistrictName : "Yeşilyurt / Tokat", CityId : 60 },
        { DistrictId : 806, DistrictName : "Başçiftlik", CityId : 60 },
        { DistrictId : 807, DistrictName : "Sulusaray", CityId : 60 },
        { DistrictId : 808, DistrictName : "Akçaabat", CityId : 61 },
        { DistrictId : 809, DistrictName : "Araklı", CityId : 61 },
        { DistrictId : 810, DistrictName : "Arsin", CityId : 61 },
        { DistrictId : 811, DistrictName : "Çaykara", CityId : 61 },
        { DistrictId : 812, DistrictName : "Maçka", CityId : 61 },
        { DistrictId : 813, DistrictName : "Of", CityId : 61 },
        { DistrictId : 814, DistrictName : "Sürmene", CityId : 61 },
        { DistrictId : 815, DistrictName : "Tonya", CityId : 61 },
        { DistrictId : 816, DistrictName : "Vakfıkebir", CityId : 61 },
        { DistrictId : 817, DistrictName : "Yomra", CityId : 61 },
        { DistrictId : 818, DistrictName : "Beşikdüzü", CityId : 61 },
        { DistrictId : 819, DistrictName : "Şalpazarı", CityId : 61 },
        { DistrictId : 820, DistrictName : "Çarşıbaşı", CityId : 61 },
        { DistrictId : 821, DistrictName : "Dernekpazarı", CityId : 61 },
        { DistrictId : 822, DistrictName : "Düzköy", CityId : 61 },
        { DistrictId : 823, DistrictName : "Hayrat", CityId : 61 },
        { DistrictId : 824, DistrictName : "Köprübaşı / Trabzon", CityId : 61 },
        { DistrictId : 825, DistrictName : "Ortahisar", CityId : 61 },
        { DistrictId : 826, DistrictName : "Çemişgezek", CityId : 62 },
        { DistrictId : 827, DistrictName : "Hozat", CityId : 62 },
        { DistrictId : 828, DistrictName : "Mazgirt", CityId : 62 },
        { DistrictId : 829, DistrictName : "Nazımiye", CityId : 62 },
        { DistrictId : 830, DistrictName : "Ovacık / Tunceli", CityId : 62 },
        { DistrictId : 831, DistrictName : "Pertek", CityId : 62 },
        { DistrictId : 832, DistrictName : "Pülümür", CityId : 62 },
        { DistrictId : 833, DistrictName : "Tunceli Merkez", CityId : 62 },
        { DistrictId : 834, DistrictName : "Akçakale", CityId : 63 },
        { DistrictId : 835, DistrictName : "Birecik", CityId : 63 },
        { DistrictId : 836, DistrictName : "Bozova", CityId : 63 },
        { DistrictId : 837, DistrictName : "Ceylanpınar", CityId : 63 },
        { DistrictId : 838, DistrictName : "Halfeti", CityId : 63 },
        { DistrictId : 839, DistrictName : "Hilvan", CityId : 63 },
        { DistrictId : 840, DistrictName : "Siverek", CityId : 63 },
        { DistrictId : 841, DistrictName : "Suruç", CityId : 63 },
        { DistrictId : 842, DistrictName : "Viranşehir", CityId : 63 },
        { DistrictId : 843, DistrictName : "Harran", CityId : 63 },
        { DistrictId : 844, DistrictName : "Eyyübiye", CityId : 63 },
        { DistrictId : 845, DistrictName : "Haliliye", CityId : 63 },
        { DistrictId : 846, DistrictName : "Karaköprü", CityId : 63 },
        { DistrictId : 847, DistrictName : "Banaz", CityId : 64 },
        { DistrictId : 848, DistrictName : "Eşme", CityId : 64 },
        { DistrictId : 849, DistrictName : "Karahallı", CityId : 64 },
        { DistrictId : 850, DistrictName : "Sivaslı", CityId : 64 },
        { DistrictId : 851, DistrictName : "Ulubey / Uşak", CityId : 64 },
        { DistrictId : 852, DistrictName : "Uşak Merkez", CityId : 64 },
        { DistrictId : 853, DistrictName : "Başkale", CityId : 65 },
        { DistrictId : 854, DistrictName : "Çatak", CityId : 65 },
        { DistrictId : 855, DistrictName : "Erciş", CityId : 65 },
        { DistrictId : 856, DistrictName : "Gevaş", CityId : 65 },
        { DistrictId : 857, DistrictName : "Gürpınar", CityId : 65 },
        { DistrictId : 858, DistrictName : "Muradiye", CityId : 65 },
        { DistrictId : 859, DistrictName : "Özalp", CityId : 65 },
        { DistrictId : 860, DistrictName : "Bahçesaray", CityId : 65 },
        { DistrictId : 861, DistrictName : "Çaldıran", CityId : 65 },
        { DistrictId : 862, DistrictName : "Edremit / Van", CityId : 65 },
        { DistrictId : 863, DistrictName : "Saray / Van", CityId : 65 },
        { DistrictId : 864, DistrictName : "İpekyolu", CityId : 65 },
        { DistrictId : 865, DistrictName : "Tuşba", CityId : 65 },
        { DistrictId : 866, DistrictName : "Akdağmadeni", CityId : 66 },
        { DistrictId : 867, DistrictName : "Boğazlıyan", CityId : 66 },
        { DistrictId : 868, DistrictName : "Çayıralan", CityId : 66 },
        { DistrictId : 869, DistrictName : "Çekerek", CityId : 66 },
        { DistrictId : 870, DistrictName : "Sarıkaya", CityId : 66 },
        { DistrictId : 871, DistrictName : "Sorgun", CityId : 66 },
        { DistrictId : 872, DistrictName : "Şefaatli", CityId : 66 },
        { DistrictId : 873, DistrictName : "Yerköy", CityId : 66 },
        { DistrictId : 874, DistrictName : "Yozgat Merkez", CityId : 66 },
        { DistrictId : 875, DistrictName : "Aydıncık / Yozgat", CityId : 66 },
        { DistrictId : 876, DistrictName : "Çandır", CityId : 66 },
        { DistrictId : 877, DistrictName : "Kadışehri", CityId : 66 },
        { DistrictId : 878, DistrictName : "Saraykent", CityId : 66 },
        { DistrictId : 879, DistrictName : "Yenifakılı", CityId : 66 },
        { DistrictId : 880, DistrictName : "Çaycuma", CityId : 67 },
        { DistrictId : 881, DistrictName : "Devrek", CityId : 67 },
        { DistrictId : 882, DistrictName : "Ereğli / Zonguldak", CityId : 67 },
        { DistrictId : 883, DistrictName : "Zonguldak Merkez", CityId : 67 },
        { DistrictId : 884, DistrictName : "Alaplı", CityId : 67 },
        { DistrictId : 885, DistrictName : "Gökçebey", CityId : 67 },
        { DistrictId : 886, DistrictName : "Kilimli", CityId : 67 },
        { DistrictId : 887, DistrictName : "Kozlu", CityId : 67 },
        { DistrictId : 888, DistrictName : "Aksaray Merkez", CityId : 68 },
        { DistrictId : 889, DistrictName : "Ortaköy / Aksaray", CityId : 68 },
        { DistrictId : 890, DistrictName : "Ağaçören", CityId : 68 },
        { DistrictId : 891, DistrictName : "Güzelyurt", CityId : 68 },
        { DistrictId : 892, DistrictName : "Sarıyahşi", CityId : 68 },
        { DistrictId : 893, DistrictName : "Eskil", CityId : 68 },
        { DistrictId : 894, DistrictName : "Gülağaç", CityId : 68 },
        { DistrictId : 895, DistrictName : "Bayburt Merkez", CityId : 69 },
        { DistrictId : 896, DistrictName : "Aydıntepe", CityId : 69 },
        { DistrictId : 897, DistrictName : "Demirözü", CityId : 69 },
        { DistrictId : 898, DistrictName : "Ermenek", CityId : 70 },
        { DistrictId : 899, DistrictName : "Karaman Merkez", CityId : 70 },
        { DistrictId : 900, DistrictName : "Ayrancı", CityId : 70 },
        { DistrictId : 901, DistrictName : "Kazımkarabekir", CityId : 70 },
        { DistrictId : 902, DistrictName : "Başyayla", CityId : 70 },
        { DistrictId : 903, DistrictName : "Sarıveliler", CityId : 70 },
        { DistrictId : 904, DistrictName : "Delice", CityId : 71 },
        { DistrictId : 905, DistrictName : "Keskin", CityId : 71 },
        { DistrictId : 906, DistrictName : "Kırıkkale Merkez", CityId : 71 },
        { DistrictId : 907, DistrictName : "Sulakyurt", CityId : 71 },
        { DistrictId : 908, DistrictName : "Bahşili", CityId : 71 },
        { DistrictId : 909, DistrictName : "Balışeyh", CityId : 71 },
        { DistrictId : 910, DistrictName : "Çelebi", CityId : 71 },
        { DistrictId : 911, DistrictName : "Karakeçili", CityId : 71 },
        { DistrictId : 912, DistrictName : "Yahşihan", CityId : 71 },
        { DistrictId : 913, DistrictName : "Batman Merkez", CityId : 72 },
        { DistrictId : 914, DistrictName : "Beşiri", CityId : 72 },
        { DistrictId : 915, DistrictName : "Gercüş", CityId : 72 },
        { DistrictId : 916, DistrictName : "Kozluk", CityId : 72 },
        { DistrictId : 917, DistrictName : "Sason", CityId : 72 },
        { DistrictId : 918, DistrictName : "Hasankeyf", CityId : 72 },
        { DistrictId : 919, DistrictName : "Beytüşşebap", CityId : 73 },
        { DistrictId : 920, DistrictName : "Cizre", CityId : 73 },
        { DistrictId : 921, DistrictName : "İdil", CityId : 73 },
        { DistrictId : 922, DistrictName : "Silopi", CityId : 73 },
        { DistrictId : 923, DistrictName : "Şırnak Merkez", CityId : 73 },
        { DistrictId : 924, DistrictName : "Uludere", CityId : 73 },
        { DistrictId : 925, DistrictName : "Güçlükonak", CityId : 73 },
        { DistrictId : 926, DistrictName : "Bartın Merkez", CityId : 74 },
        { DistrictId : 927, DistrictName : "Kurucaşile", CityId : 74 },
        { DistrictId : 928, DistrictName : "Ulus", CityId : 74 },
        { DistrictId : 929, DistrictName : "Amasra", CityId : 74 },
        { DistrictId : 930, DistrictName : "Ardahan Merkez", CityId : 75 },
        { DistrictId : 931, DistrictName : "Çıldır", CityId : 75 },
        { DistrictId : 932, DistrictName : "Göle", CityId : 75 },
        { DistrictId : 933, DistrictName : "Hanak", CityId : 75 },
        { DistrictId : 934, DistrictName : "Posof", CityId : 75 },
        { DistrictId : 935, DistrictName : "Damal", CityId : 75 },
        { DistrictId : 936, DistrictName : "Aralık", CityId : 76 },
        { DistrictId : 937, DistrictName : "Iğdır Merkez", CityId : 76 },
        { DistrictId : 938, DistrictName : "Tuzluca", CityId : 76 },
        { DistrictId : 939, DistrictName : "Karakoyunlu", CityId : 76 },
        { DistrictId : 940, DistrictName : "Yalova Merkez", CityId : 77 },
        { DistrictId : 941, DistrictName : "Altınova", CityId : 77 },
        { DistrictId : 942, DistrictName : "Armutlu", CityId : 77 },
        { DistrictId : 943, DistrictName : "Çınarcık", CityId : 77 },
        { DistrictId : 944, DistrictName : "Çiftlikköy", CityId : 77 },
        { DistrictId : 945, DistrictName : "Termal", CityId : 77 },
        { DistrictId : 946, DistrictName : "Eflani", CityId : 78 },
        { DistrictId : 947, DistrictName : "Eskipazar", CityId : 78 },
        { DistrictId : 948, DistrictName : "Karabük Merkez", CityId : 78 },
        { DistrictId : 949, DistrictName : "Ovacık / Karabük", CityId : 78 },
        { DistrictId : 950, DistrictName : "Safranbolu", CityId : 78 },
        { DistrictId : 951, DistrictName : "Yenice / Karabük", CityId : 78 },
        { DistrictId : 952, DistrictName : "Kilis Merkez", CityId : 79 },
        { DistrictId : 953, DistrictName : "Elbeyli", CityId : 79 },
        { DistrictId : 954, DistrictName : "Musabeyli", CityId : 79 },
        { DistrictId : 955, DistrictName : "Polateli", CityId : 79 },
        { DistrictId : 956, DistrictName : "Bahçe", CityId : 80 },
        { DistrictId : 957, DistrictName : "Kadirli", CityId : 80 },
        { DistrictId : 958, DistrictName : "Osmaniye Merkez", CityId : 80 },
        { DistrictId : 959, DistrictName : "Düziçi", CityId : 80 },
        { DistrictId : 960, DistrictName : "Hasanbeyli", CityId : 80 },
        { DistrictId : 961, DistrictName : "Sumbas", CityId : 80 },
        { DistrictId : 962, DistrictName : "Toprakkale", CityId : 80 },
        { DistrictId : 963, DistrictName : "Akçakoca", CityId : 81 },
        { DistrictId : 964, DistrictName : "Düzce Merkez", CityId : 81 },
        { DistrictId : 965, DistrictName : "Yığılca", CityId : 81 },
        { DistrictId : 966, DistrictName : "Cumayeri", CityId : 81 },
        { DistrictId : 967, DistrictName : "Gölyaka", CityId : 81 },
        { DistrictId : 968, DistrictName : "Çilimli", CityId : 81 },
        { DistrictId : 969, DistrictName : "Gümüşova", CityId : 81 },
        { DistrictId : 970, DistrictName : "Kaynaşlı", CityId : 81 }
        ];
        return districts;

    }

    const dbstuff = {
        City :City,
        District: District,
        createDummyDistrict : createDummyDistrict,
        createDummyCity : createDummyCity,
    };
    module.exports = dbstuff